### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by mbaechtold**
⚠️ This also drops support for Python 2 since Python 2 is not (officially) maintained anymore.

Closes https://github.com/devartis/passbook/issues/40 and https://github.com/devartis/passbook/issues/49

### CODE REVIEW

**Comment by bimusiek** [comment]
Did anyone try using it on production?

**Comment by mbaechtold** [comment]
Not me.

**Comment by bimusiek** [comment]
Thanks for so swift reply, I will try it out and see if there are any issues.

**Comment by mbaechtold** [comment]
Any feedback would be greatly appreciated.

**Comment by mbaechtold** [comment]
`m2crypto` finally released Python 3 support.

**Comment by Fraterius** [comment]
I think it would be a good practice to leave backward compatibility with python 2. Thanks for moving passbook into python 3. If I encounter any problems I'll report back here.

**Comment by mbaechtold** [comment]
@Fraterius, thanks for giving it a try.

Python 2 will be maintained until 2020. Until then, we should support it too, yes.

**Comment by antwan** [comment]
What's blocking this PR?

**Comment by pablo-moreno** [comment]
Hi, any update on this?

**Comment by mbaechtold** [comment]
I'm confident, that this should work on Python 3 now. I was able to generate a valid PkPass file with my Apple developer account. 

Could anybody please try it out on your machines by installing the package directly from my fork on GitHub (https://github.com/mbaechtold/passbook/tree/python3-m2crypto)?

⚠️ As discussed in #49, I have removed support for Python 2.

**Comment by mbaechtold** [comment]
@fara, I propose to merge this. Are you okay with it?

**Comment by fara** [comment]
@mbaechtold tried your branch locally and all tests pass. The PR looks good. You should add yourself in the credits section of the README.md file and then go ahead and merge

**Comment by bartoszhernas** [comment]
GetPassbook.com was using this fork for months with Python3, so I would say it's safe to release :) (learned now after our CI broke due to missing fork branch ;)

**Comment by mbaechtold** [comment]
Hey @bartoszhernas, thank you very much for reporting in. Glad to hear it is working and helpful to you!

**Pull request merged**
